# Edit these
# -----------------------------------------------------------------------
profilePicture = "images/Purdue.jpg"
title = "Elizabeth Teas, MS"
description = ""
author = "Elizabeth Teas"
copyright = "2021"

[[socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://www.twitter.com/esohns"

[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/elizabeth_teas"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:eteas@purdue.edu"


# Ignore these
# ------------------------------------------------------------------------
keywords = ""
favicon = "favicons/"
enableMediumZoom = false

doNotLoadAnimations = false

singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"

# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".


